url: "https://www.tedsanders.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ted Sanders"
permalink: /:title/
repository: tedsanders.github.io