name:        Ted Sanders
description: Ted Sanders is a technologist who believes the best way to predict the future is to study the past. He's earning a PhD in Applied Physics from Stanford and holds an MS in Applied Science and Technology from UC Berkeley.

url:         http://www.tedsanders.com
author:      Ted Sanders

future:      false
show_drafts: false


relative_permalinks: false

permalink:     :categories/:title
paginate_path: 'page:num'
paginate: 10

markdown: kramdown
