name:        Ted Sanders
description: The impersonal website of Ted Sanders.
url:         http://127.0.0.1:4000
author:      Ted Sanders

future:      true
show_drafts: true
limit_posts: 0
pygments:    true

relative_permalinks: false

permalink:     :title
paginate_path: 'page:num'
paginate: 100