name: Ted Sanders
description: The impersonal website of Ted Sanders.
url: http://tedsanders.github.io/
author: Ted Sanders


future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     :title/index.html
paginate_path: 'page:num'
paginate: 1